### PR TITLE
Update paper.md

### PR DESCRIPTION
**Pull request by arfon**
👋 @keblu - this fixes the paper metadata so it's compatible with our submission process.

### CODE REVIEW

**Comment by ArdiaD** [comment]
Thanks a lot @arfon  for your help! Thanks again @braverock for your fast review.

**Comment by ArdiaD** [comment]
@arfon seems to be an issue with doi2bib. Can you check on your side, but while clicking on it, it is unable to generate the bib citation reference. thanks

**Comment by arfon** [comment]
> @arfon seems to be an issue with doi2bib. Can you check on your side, but while clicking on it, it is unable to generate the bib citation reference. thanks

It seems to take a few hours for the doi2bib link to start working (I suspect they only sync Crossref data every few hours or something)?

**Comment by ArdiaD** [comment]
OK, I see. Thanks!

**Pull request merged**
